# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bitcoin/grpc/grpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bitcoin.grpc.WatchTxConfirmedRequest" do
    optional :id, :uint32, 1
    optional :tx_hash, :string, 2
    optional :confirmations, :uint32, 3
  end
  add_message "bitcoin.grpc.WatchTxConfirmedResponse" do
    optional :id, :uint32, 1
    oneof :event do
      optional :confirmed, :message, 2, "bitcoin.grpc.EventTxConfirmed"
    end
  end
  add_message "bitcoin.grpc.WatchUtxoRequest" do
    optional :id, :uint32, 1
  end
  add_message "bitcoin.grpc.WatchUtxoResponse" do
    optional :id, :uint32, 1
    oneof :event do
      optional :registered, :message, 2, "bitcoin.grpc.EventUtxoRegistered"
      optional :spent, :message, 3, "bitcoin.grpc.EventUtxoSpent"
    end
  end
  add_message "bitcoin.grpc.WatchTokenRequest" do
    optional :id, :uint32, 1
    optional :asset_type, :bytes, 2
  end
  add_message "bitcoin.grpc.WatchTokenResponse" do
    optional :id, :uint32, 1
    oneof :event do
      optional :issued, :message, 2, "bitcoin.grpc.EventTokenIssued"
      optional :transfered, :message, 3, "bitcoin.grpc.EventTokenTransfered"
      optional :burned, :message, 4, "bitcoin.grpc.EventTokenBurned"
    end
  end
  add_message "bitcoin.grpc.WatchAssetIdAssignedRequest" do
    optional :tx_hash, :string, 1
    optional :tx_payload, :string, 2
  end
  add_message "bitcoin.grpc.EventTxConfirmed" do
    optional :request_id, :uint32, 1
    optional :tx_hash, :string, 2
    optional :tx_payload, :string, 3
    optional :block_height, :uint32, 4
    optional :tx_index, :uint32, 5
    optional :confirmations, :uint32, 6
  end
  add_message "bitcoin.grpc.EventUtxoRegistered" do
    optional :request_id, :uint32, 1
    optional :tx_hash, :string, 2
    optional :tx_payload, :string, 3
    optional :utxo, :message, 4, "bitcoin.grpc.Utxo"
  end
  add_message "bitcoin.grpc.EventUtxoSpent" do
    optional :request_id, :uint32, 1
    optional :tx_hash, :string, 2
    optional :tx_payload, :string, 3
    optional :utxo, :message, 4, "bitcoin.grpc.Utxo"
  end
  add_message "bitcoin.grpc.EventTokenIssued" do
    optional :request_id, :uint32, 1
    optional :asset, :message, 2, "bitcoin.grpc.AssetOutput"
  end
  add_message "bitcoin.grpc.EventTokenTransfered" do
    optional :request_id, :uint32, 1
    optional :asset, :message, 2, "bitcoin.grpc.AssetOutput"
  end
  add_message "bitcoin.grpc.EventTokenBurned" do
    optional :request_id, :uint32, 1
    optional :asset, :message, 4, "bitcoin.grpc.AssetOutput"
  end
  add_message "bitcoin.grpc.Utxo" do
    optional :tx_hash, :string, 1
    optional :index, :uint32, 2
    optional :block_height, :uint32, 3
    optional :value, :uint64, 4
    optional :script_pubkey, :string, 5
  end
  add_message "bitcoin.grpc.AssetOutput" do
    optional :asset_type, :bytes, 1
    optional :asset_id, :string, 2
    optional :asset_quantity, :uint64, 3
    optional :tx_hash, :string, 4
    optional :index, :uint32, 5
    optional :block_height, :uint32, 6
  end
end

module Bitcoin
  module Grpc
    WatchTxConfirmedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchTxConfirmedRequest").msgclass
    WatchTxConfirmedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchTxConfirmedResponse").msgclass
    WatchUtxoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchUtxoRequest").msgclass
    WatchUtxoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchUtxoResponse").msgclass
    WatchTokenRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchTokenRequest").msgclass
    WatchTokenResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchTokenResponse").msgclass
    WatchAssetIdAssignedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.WatchAssetIdAssignedRequest").msgclass
    EventTxConfirmed = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventTxConfirmed").msgclass
    EventUtxoRegistered = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventUtxoRegistered").msgclass
    EventUtxoSpent = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventUtxoSpent").msgclass
    EventTokenIssued = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventTokenIssued").msgclass
    EventTokenTransfered = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventTokenTransfered").msgclass
    EventTokenBurned = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.EventTokenBurned").msgclass
    Utxo = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.Utxo").msgclass
    AssetOutput = Google::Protobuf::DescriptorPool.generated_pool.lookup("bitcoin.grpc.AssetOutput").msgclass
  end
end
